### PR TITLE
Hookups between models.py, views.py, and urls.py. Some tests for models.py. (Location, Station, Appointment, Profile models currently used to demonstrate the structure but will eventually be updated to match original FreeGeek database.)

### PR DESCRIPTION
**Pull request by mbrochmann**
Improved station and location and appointment creation functions.

Note I moved admin.py to admin.py.HIDE because its code was causing me some run problems.

I also moved test_models.py from the tests directory to the freegeek directory, simply because I was unable to figure out how to single out the test_models.py for running separately. 

("python manage.py test tests test_models" did not work for me.)

Now I just can do: python manage.py tests freegeek

We can move it back if somebody shows me how I can run only one of the test_*.py files in the tests/ directory.

### CODE REVIEW

**Comment by raehart** [comment]
looks like your models_test.py file is in the wrong location.  Should be under /tests not under freegeek/

**Comment by mbrochmann** [comment]
yeah, see my notes above. I couldn't figure out how to run *only* test_models.py when it was in the tests directory so i moved it.

**Comment by raehart** [comment]
Okay in the end I think we should put them under tests and delete that file, but its probably fine for now.

**Comment by mbrochmann** [comment]
if you can help me figure out how I can run only one of the test_*.py files in the tests/ directory, that would be awesome. i tried various versions of what i saw at the end of the test_models.py file (and tried searching online) but couldn't figure it out.

**Comment by raehart** [comment]
In theory python manage.py test tests file name should work, and I can totally do that once I get my tests passing.

**Comment by mbrochmann** [comment]
ok, let me know. i've tried all the variants of the suggested command i can think of. :)

also btw, i had some trouble getting the separate "setup" bit in the individual test classes to work, so i just put all the testing into functions, as they do at:

https://docs.djangoproject.com/en/1.11/intro/tutorial05/

this is probably the most rudimentary way to test but it works for now. :)

**Comment by mbrochmann** [comment]
to run only the tests in tests/test_models.py, do:
python manage.py test tests.test_models

to seed the empty database, do (from the python shell):
exec(open("./seed_database.py").read())

**Comment by mbrochmann** [comment]
Closing this PR as it is experimental/learning stuff mostly - moving it all to my own personal fork of free-geek.

**Pull request closed without merging**
